---
# templates/secret.yaml
{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: blockfrost-secrets
type: Opaque
stringData:
  secret: "{{ .Values.secrets.secret }}"
  rewardAddress: "{{ .Values.secrets.rewardAddress }}"
{{- end }}
