---
# templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ include "blockfrost-platform.fullname" . }}
spec:
  selector:
    app: {{ include "blockfrost-platform.fullname" . }}
  ports:
    - name: api
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  type: ClusterIP
