---
# templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ include "blockfrost-platform.fullname" . }}
  labels:
    {{- include "blockfrost-platform.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "blockfrost-platform.selectorLabels" . | nindent 4 }}
  ports:
    - name: api
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  type: ClusterIP
